import { expect, it, vi } from "vitest";
import { sharedDelivery, SharedDelivery, type SharedDeliverySnapshot } from "./shared-delivery";
const file = (name: string) => ({ name } as File);
it("retains files, failed state and the exact send identity across composer remounts", async () => {
  const key = `room-${crypto.randomUUID()}`;
  const firstScreen = sharedDelivery(key);
  const photo = file("photo.png");
  firstScreen.setFiles(() => [photo]);
  const sent: SharedDeliverySnapshot[] = [];
  const accepted = vi.fn();
  await firstScreen.send("review", "source", async snapshot => { sent.push(snapshot); throw new Error("lost acknowledgement"); }, accepted);
  const secondScreen = sharedDelivery(key);
  expect(secondScreen.getSnapshot()).toMatchObject({ status: "failed", files: [photo] });
  await secondScreen.send("review", "source", async snapshot => { sent.push(snapshot); }, accepted);
  expect(sent[1]).toEqual(sent[0]);
  expect(accepted).toHaveBeenCalledTimes(1);
  expect(secondScreen.getSnapshot()).toMatchObject({ status: "sent", files: [] });
});
it("rejects a duplicate click while sending and preserves later attachments", async () => {
  const delivery = new SharedDelivery();
  const first = file("first.png"), next = file("next.png");
  delivery.setFiles(() => [first]);
  let finish!: () => void;
  const held = new Promise<void>(resolve => { finish = resolve; });
  const send = vi.fn(async () => held);
  const pending = delivery.send("first", undefined, send, () => {});
  expect(delivery.getSnapshot().status).toBe("sending");
  const remounted = vi.fn();
  const unsubscribe = delivery.subscribe(remounted);
  expect(await delivery.send("first", undefined, send, () => {})).toBe(false);
  delivery.setFiles(files => [...files, next]);
  finish(); await pending;
  expect(delivery.getSnapshot().files).toEqual([next]);
  expect(send).toHaveBeenCalledTimes(1);
  expect(remounted).toHaveBeenCalled();
  unsubscribe();
});
it("starts a distinct send when the reply or ordered files change", async () => {
  const delivery = new SharedDelivery();
  const ids: string[] = [];
  const fail = async (snapshot: SharedDeliverySnapshot) => { ids.push(snapshot.sendId); throw new Error("offline"); };
  const a = file("a"), b = file("b");
  delivery.setFiles(() => [a, b]);
  await delivery.send("same", "one", fail, () => {});
  await delivery.send("same", "two", fail, () => {});
  delivery.setFiles(() => [b, a]);
  await delivery.send("same", "two", fail, () => {});
  expect(new Set(ids).size).toBe(3);
});
