// Isolated fixture only: the control harness verifies its ui handle and origin.
import assert from "node:assert/strict";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import { runControlOmb } from "./control-omb.ts";
const handle = process.argv[2];
const missingChief = process.argv.includes("--missing-chief");
if (!handle) throw new Error("Usage: verify-recruitment-ui.ts /path/to/fixture/ui.json");
const ui = (verb: string, ...args: string[]) => runControlOmb(["ui", verb, "--ui", handle, ...args]) as Promise<Record<string, any>>;
const evaluate = async (js: string) => (await ui("eval", "--js", js)).result;
const snapshot = async () => (await ui("snapshot")).snapshot as string;
const click = async (name: string) => { await delay(350); return ui("click", "--name", name); };
const poll = async (read: () => Promise<any>, check: (value: any) => boolean, name: string) => {
 const end = Date.now()+20000; let value;
 do { value=await read(); if(check(value))return value; await delay(150); } while(Date.now()<end);
 throw new Error(`${name}: ${JSON.stringify(value)}`);
};
const visible = (text: string) => poll(snapshot, value=>value.includes(text), text);
const request = (method: string, path: string, body?: unknown) => evaluate(`fetch(${JSON.stringify(path)},{method:${JSON.stringify(method)},headers:{'content-type':'application/json'},${body === undefined ? "" : `body:JSON.stringify(${JSON.stringify(body)}),`}}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(JSON.stringify(data));return data})`);
const evidence = resolve(`.omb-scratch/verify-evidence/recruitment${missingChief ? "-missing-chief" : ""}`); mkdirSync(evidence,{recursive:true});
const bots = (await request("GET","/api/bots")).bots;
let original = bots.find((bot:any)=>bot.chiefOfStaff && !bot.hidden);
assert.ok(original,"fixture has a seeded chief");
const previousChiefId=original.id;
if(missingChief)await request("DELETE",`/api/bots/${original.id}`);
else await request("PATCH",`/api/bots/${original.id}`,{name:"Jarvis"});
await request("PUT","/api/config",{profile:{name:"Recruitment fixture",email:"recruitment@example.test"},onboarding:{completedAt:"2026-09-28T00:00:00.000Z",version:1}});
await evaluate("setTimeout(()=>location.reload(),0);true");
await visible("Message Pepper");
assert.equal(await evaluate("Boolean(document.querySelector('[aria-label=\"Build your AI team\"]'))"),false);
await click("Recruitment fixture"); await click("Settings"); await visible("Set up my AI team");
await click("Set up my AI team"); await visible(`${missingChief ? "BOS" : "Jarvis"} · your team coordinator`);
await ui("type","--name","What does your business do?","--text","We run a fixture bakery");
await ui("type","--name","Who do you help?","--text","Local families");
await click("Find my first teammate"); await visible("Your brief is saved");
await click("Continue"); await visible("Your first assignment");
await ui("screenshot","--out",resolve(evidence,"assignment.png"));
await click("Start my first assignment");
const saved = await poll(()=>request("GET","/api/config"),value=>Boolean(value.onboarding?.firstAssignment?.prepared),"durable assignment");
const assignment = saved.onboarding.firstAssignment;
if(missingChief){original=(await request("GET","/api/bots")).bots.find((bot:any)=>bot.id===assignment.botId);assert.ok(original);assert.notEqual(original.id,previousChiefId);}
assert.equal(assignment.botId,original.id); assert.equal(assignment.threadId,original.threadId);
assert.equal(assignment.sendId,`onboarding_${original.threadId}`);
assert.match(assignment.text,/Carry out the setup now/); assert.match(assignment.text,/coordinate_bots/);
assert.match(assignment.text,/We run a fixture bakery/); assert.match(assignment.text,/Local families/);
await visible("hello from fake claude");
const after = (await request("GET","/api/bots")).bots;
assert.equal(after.find((bot:any)=>bot.id===original.id).name,missingChief ? "BOS" : "Jarvis");
assert.equal(after.find((bot:any)=>bot.id===original.id).chiefOfStaff,true);
assert.equal(after.length,bots.length,"reuses coordinator without creating another");
const rows = (await request("GET",`/api/threads/${assignment.threadId}/messages`)).messages;
assert.equal(rows.filter((row:any)=>row.sendId===assignment.sendId).length,1);
await click("Recruitment fixture"); await click("Settings"); await click("Set up my AI team");
await visible("Resume my first assignment"); await click("Resume my first assignment");
await visible("hello from fake claude");
assert.deepEqual((await request("GET",`/api/threads/${assignment.threadId}/messages`)).messages,rows,"resume doesn't rerun completed assignment");
await ui("screenshot","--out",resolve(evidence,"first-result.png"));
const finalSnapshot = await snapshot();
writeFileSync(resolve(evidence,"result.json"),JSON.stringify({handle,chiefId:original.id,assignment,finalSnapshot,limitation:"fake engine verifies prompt delivery and UI only; specialist tool execution and output quality are not proven by this recipe"},null,2));
console.log(`PASS completed welcome -> settings team setup -> ${missingChief ? "new missing chief" : "existing Jarvis"} -> durable specialist brief -> fake response -> resume without rerun`);
console.log(`evidence: ${evidence}`);
